#!/usr/bin/env python3
"""Sync the dme package into the Python Worker probe, then deploy it.

    python scripts/build_worker.py
    cd deploy/py && uv run pywrangler deploy

The package is copied rather than committed twice: `deploy/py/src/dme` is
gitignored, so there is exactly one copy of the spine in this repo and the
Worker is always testing the real thing.
"""

from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "deploy" / "py" / "src" / "dme"

# The Worker probe exercises the deterministic half. These need a socket or a
# thread, neither of which exists in Pyodide -- see deploy/README.md.
# Nothing is excluded: every module imports cleanly on Pyodide. web.py pulls in
# http.server and export.py reads viewer templates, but both only touch those at
# call time, and the Worker calls neither -- it uses run_case_streaming directly.
EXCLUDE: set[str] = set()


DATA_FILES = ("suppliers.csv", "case_eleanor.json")


def bundle_data() -> str:
    """Inline the fixture files, because a Worker has no filesystem."""
    entries = []
    for name in DATA_FILES:
        text = (ROOT / "data" / name).read_text(encoding="utf-8")
        entries.append(f"    {name!r}: {text!r},")
    body = "\n".join(entries)
    return (
        '"""Generated by scripts/build_worker.py -- do not edit.\n\n'
        "The data/ fixtures, inlined for environments with no filesystem.\n"
        '"""\n\nFILES = {\n' + body + "\n}\n"
    )


def main() -> int:
    if TARGET.exists():
        shutil.rmtree(TARGET)
    shutil.copytree(
        ROOT / "dme", TARGET,
        ignore=shutil.ignore_patterns("__pycache__", *EXCLUDE) if EXCLUDE
        else shutil.ignore_patterns("__pycache__"),
    )
    (TARGET / "_bundled_data.py").write_text(bundle_data(), encoding="utf-8")

    # The app is served as static assets; app.html becomes the index.
    public = ROOT / "deploy" / "py" / "public"
    public.mkdir(parents=True, exist_ok=True)
    shutil.copy(ROOT / "viewer" / "app.html", public / "index.html")
    for name in ("style.css", "replay.js"):
        shutil.copy(ROOT / "viewer" / name, public / name)
    kept = sorted(p.relative_to(TARGET).as_posix() for p in TARGET.rglob("*.py"))
    print(f"  synced {len(kept)} modules into {TARGET.relative_to(ROOT)}")
    print(f"  excluded: {', '.join(sorted(EXCLUDE)) or 'nothing'}")
    print("  deploy with:  cd deploy/py && uv run pywrangler deploy")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
